// Auto-generated by vitest-native — do not edit
// Set mode BEFORE importing the harness (it reads this synchronously)
globalThis.__VITEST_NATIVE_MODE__ = "run";

// Polyfill browser globals that some vitest/chai deps expect
if (typeof globalThis.window === 'undefined') globalThis.window = globalThis;
if (typeof globalThis.self === 'undefined') globalThis.self = globalThis;

import { AppRegistry } from 'react-native';
import { createTestHarness } from 'vitest-react-native-runtime/runtime';

const HarnessApp = createTestHarness();
AppRegistry.registerComponent('VitestNativeHarness', () => HarnessApp);
