import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      'node/index': 'src/node/index.ts',
      'node/pool': 'src/node/pool.ts',

      'node/environment': 'src/node/environment.ts',
      'node/device': 'src/node/device.ts',
    },
    format: ['esm', 'cjs'],
    dts: false,
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: true,
    shims: true,
    external: ['metro', 'metro-config', 'node-pty'],
  },
  {
    entry: {
      'runtime/index': 'src/runtime/index.ts',
      'runtime/vitest-shim': 'src/runtime/vitest-shim.ts',
    },
    format: ['cjs'],
    outDir: 'dist',
    target: 'es2022',
    platform: 'neutral',
    splitting: false,
    sourcemap: true,
    clean: false,
    external: [
      'react',
      'react-native',
      '@vitest/runner',
      '@vitest/expect',
      '@vitest/utils',
      'birpc',
      'flatted',
      'chai',
      'vitest-react-native-runtime/test-registry',
      '@shopify/restyle',
    ],
  },
  {
    entry: { 'babel/test-wrapper-plugin': 'src/babel/test-wrapper-plugin.ts' },
    format: ['cjs'],
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: false,
  },
  {
    entry: { 'metro/withNativeTests': 'src/metro/withNativeTests.ts' },
    format: ['cjs'],
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: false,
  },
  {
    entry: { 'cli/index': 'src/cli/index.ts' },
    format: ['esm'],
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: false,
    banner: { js: '#!/usr/bin/env node' },
  },
  {
    entry: {
      'cli/doctor': 'src/cli/doctor.ts',
      'cli/init': 'src/cli/init.ts',
      'cli/resume': 'src/cli/resume.ts',
      'cli/debug': 'src/cli/debug.ts',
      'cli/status': 'src/cli/status.ts',
      'cli/logs': 'src/cli/logs.ts',
      'cli/kill': 'src/cli/kill.ts',
      'cli/tap': 'src/cli/tap.ts',
      'cli/type-text': 'src/cli/type-text.ts',
      'cli/tree': 'src/cli/tree.ts',
      'cli/console': 'src/cli/console.ts',
      'cli/start': 'src/cli/start.ts',
    },
    format: ['esm'],
    outDir: 'dist',
    target: 'node18',
    platform: 'node',
    splitting: false,
    sourcemap: true,
    clean: false,
  },
]);
