/**
 * metro-runner — starts Metro programmatically, configured for test execution.
 *
 * Replaces the previous approach of spawning `npx expo start --dev-client`.
 * The user doesn't need metro.config.js or babel.config.js — all configuration
 * is applied programmatically by the pool.
 */

import { resolve } from 'node:path';
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { log } from './logger';
import { generateTestRegistry } from '../metro/generateTestRegistry';

function resolveFromProject(projectRoot: string, modulePath: string): string {
  const req = createRequire(resolve(projectRoot, '_resolver.js'));
  return req.resolve(modulePath);
}

function findInNodeModules(startDir: string, modulePath: string): string | null {
  let dir = startDir;
  for (;;) {
    const candidate = resolve(dir, 'node_modules', modulePath);
    if (existsSync(candidate)) return candidate;
    const parent = resolve(dir, '..');
    if (parent === dir) return null;
    dir = parent;
  }
}

// ── Types ──────────────────────────────────────────────────────────

export interface MetroRunnerOptions {
  /** User's project root (where test files live). */
  projectRoot: string;
  /** Port for Metro HTTP/WS server. */
  port: number;
  /** Target platform. */
  platform: 'ios' | 'android';
  /** Glob patterns for test file discovery. */
  testPatterns: string[];
  /** Module name the harness app registers (for entry point). */
  appModuleName: string;
  /** Harness mode ('run' | 'dev'). */
  mode?: string;
}

export interface MetroServer {
  /** Stop the Metro server. */
  close(): Promise<void>;
  /** Port the server is listening on. */
  port: number;
}

// ── Public API ─────────────────────────────────────────────────────

/**
 * Start a Metro dev server configured for test execution.
 *
 * 1. Generates the entry point (index.js in project root)
 * 2. Generates babel.config.js if none exists
 * 3. Generates the test registry (.vitest-native/test-imports.generated.js)
 * 4. Loads Metro config (user's or defaults)
 * 5. Applies test transforms (vitest shim, resolver)
 * 6. Starts Metro.runServer() and waits until ready
 */
export async function startMetroServer(options: MetroRunnerOptions): Promise<MetroServer> {
  const { projectRoot, port, testPatterns, appModuleName, mode } = options;

  // Ensure .vitest-native dir exists
  const outputDir = resolve(projectRoot, '.vitest-native');
  mkdirSync(outputDir, { recursive: true });
  const gitignorePath = resolve(outputDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, '*\n');
  }

  // 1. Generate entry point as index.js in project root.
  // This is what the app requests as /index.bundle — standard Metro convention.
  const entryPath = resolve(projectRoot, 'index.js');
  generateEntryPoint(entryPath, appModuleName, mode);
  log.verbose(`Generated entry point: ${entryPath}`);

  // 2. Generate babel config (if user doesn't have one)
  ensureBabelConfig(projectRoot);

  // 3. Generate test registry
  const { filePath: registryPath, testFiles } = generateTestRegistry({
    projectRoot,
    testPatterns,
    outputDir,
    mode,
  });
  log.info(`Discovered ${testFiles.length} test file(s)`);

  // 4. Load Metro config
  const Metro = await import('metro');
  const { loadConfig } = await import('metro-config');
  let baseConfig: any;

  // Check for user-provided metro config
  const userConfigPaths = ['metro.config.js', 'metro.config.cjs'];
  let userConfigPath: string | null = null;
  for (const name of userConfigPaths) {
    const p = resolve(projectRoot, name);
    if (existsSync(p)) { userConfigPath = p; break; }
  }

  if (userConfigPath) {
    log.verbose(`Loading user ${userConfigPath}`);
    baseConfig = await loadConfig({ config: userConfigPath }, { projectRoot });
  } else {
    // Generate a metro config that uses @react-native/metro-config
    const generatedMetroConfig = resolve(outputDir, 'metro.config.cjs');
    const metroConfigContent = `// Auto-generated by vitest-native
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config');
module.exports = getDefaultConfig(${JSON.stringify(projectRoot)});
`;
    writeFileSync(generatedMetroConfig, metroConfigContent);
    log.verbose('Loading generated metro config with RN defaults');
    baseConfig = await loadConfig({ config: generatedMetroConfig }, { projectRoot });
  }

  // 5. Apply test transforms
  const config = applyTestTransforms(baseConfig, {
    projectRoot,
    registryPath,
    outputDir,
  });

  config.server = config.server ?? {};
  config.server.port = port;

  // Metro v0.83+ doesn't serve /status by default, but RCTBundleURLProvider
  // checks it to confirm the packager is running before loading the bundle.
  const existingMiddleware = config.server.enhanceMiddleware;
  config.server.enhanceMiddleware = (middleware: any, metroServer: any) => {
    const enhanced = existingMiddleware
      ? existingMiddleware(middleware, metroServer)
      : middleware;
    return (req: any, res: any, next: any) => {
      if (req.url === '/status') {
        res.writeHead(200, { 'Content-Type': 'text/plain' });
        res.end('packager-status:running');
        return;
      }
      enhanced(req, res, next);
    };
  };

  // Set environment for the harness runtime
  process.env.VITEST_NATIVE_MODE = mode ?? 'run';

  // 6. Start Metro and wait for it to be ready
  log.info(`Starting Metro on port ${port}...`);

  let httpServer: any;
  await new Promise<void>((resolveReady, reject) => {
    Metro.default.runServer(config, {
      host: '127.0.0.1',
      onReady: () => {
        log.info(`Metro ready on port ${port}`);
        resolveReady();
      },
    }).then((server: any) => {
      httpServer = server;
    }).catch(reject);
  });

  // Verify Metro is serving (try both legacy and modern endpoints)
  try {
    const res = await fetch(`http://127.0.0.1:${port}/status`);
    const text = await res.text();
    if (text.includes('packager-status:running')) {
      log.verbose('Metro /status OK');
    } else {
      // Metro v0.83+ may not have /status — try a simple health check
      log.verbose('Metro /status not available, trying health check...');
    }
  } catch (e) {
    log.verbose(`Metro health check: ${e}`);
  }

  return {
    port,
    async close() {
      log.verbose('Metro close requested');
      if (httpServer) {
        await new Promise<void>((r) => {
          httpServer.close(() => r());
          setTimeout(r, 3000);
        });
        httpServer = null;
        log.verbose('Metro server closed');
      }
    },
  };
}

// ── Babel Config Generation ───────────────────────────────────────

function ensureBabelConfig(projectRoot: string): void {
  // Check all babel config variants
  const babelConfigs = ['babel.config.js', 'babel.config.cjs', 'babel.config.json', '.babelrc', '.babelrc.js', '.babelrc.json'];
  for (const name of babelConfigs) {
    if (existsSync(resolve(projectRoot, name))) {
      log.verbose(`Using existing ${name}`);
      return;
    }
  }

  // Only add our test-wrapper plugin. The RN babel preset is configured by
  // @react-native/metro-config (loaded in step 4). Adding the preset here too
  // would cause "more than one plugin attempted to override parsing".
  // Use .cjs extension to avoid issues with "type": "module" in package.json.
  const babelConfigPath = resolve(projectRoot, 'babel.config.cjs');
  const content = `// Auto-generated by vitest-native — do not edit
module.exports = {
  plugins: ['vitest-react-native-runtime/babel-plugin'],
};
`;
  writeFileSync(babelConfigPath, content);
  log.info('Generated babel.config.cjs');
}

// ── Entry Point Generation ─────────────────────────────────────────

function generateEntryPoint(entryPath: string, appModuleName: string, mode?: string): void {
  const effectiveMode = mode ?? 'run';
  const content = `// Auto-generated by vitest-native — do not edit
// Set mode BEFORE importing the harness (it reads this synchronously)
globalThis.__VITEST_NATIVE_MODE__ = ${JSON.stringify(effectiveMode)};

// Polyfill browser globals that some vitest/chai deps expect
if (typeof globalThis.window === 'undefined') globalThis.window = globalThis;
if (typeof globalThis.self === 'undefined') globalThis.self = globalThis;

import { AppRegistry } from 'react-native';
import { createTestHarness } from 'vitest-react-native-runtime/runtime';

const HarnessApp = createTestHarness();
AppRegistry.registerComponent('${appModuleName}', () => HarnessApp);
`;

  let existing = '';
  try { existing = readFileSync(entryPath, 'utf8'); } catch {}
  if (existing !== content) {
    writeFileSync(entryPath, content);
  }
}

// ── Metro Config Transforms ────────────────────────────────────────

function applyTestTransforms(
  config: any,
  options: {
    projectRoot: string;
    registryPath: string;
    outputDir: string;
  },
): any {
  const { projectRoot, registryPath } = options;

  // Resolver setup
  config.resolver = config.resolver ?? {};

  // Enable package exports with react-native condition
  config.resolver.unstable_enablePackageExports = true;
  const conditions: string[] = config.resolver.unstable_conditionNames ?? [];
  for (const c of ['react-native', 'require', 'default']) {
    if (!conditions.includes(c)) conditions.push(c);
  }
  config.resolver.unstable_conditionNames = conditions;

  // Custom module resolution
  const originalResolver = config.resolver.resolveRequest;
  config.resolver.resolveRequest = (context: any, moduleName: string, platform: string | null) => {
    // Redirect test-registry to our generated file
    if (moduleName === 'vitest-react-native-runtime/test-registry') {
      return { type: 'sourceFile', filePath: registryPath };
    }

    // Redirect `vitest` to our shim
    if (moduleName === 'vitest') {
      return context.resolveRequest(context, 'vitest-react-native-runtime/vitest-shim', platform);
    }

    if (originalResolver) {
      return originalResolver(context, moduleName, platform);
    }
    return context.resolveRequest(context, moduleName, platform);
  };

  config.projectRoot = projectRoot;

  // Ensure InitializeCore runs before the main module (registers HMRClient, AppRegistry, etc.)
  config.serializer = config.serializer ?? {};
  if (!config.serializer.getModulesRunBeforeMainModule) {
    const initCorePath = findInNodeModules(projectRoot, 'react-native/Libraries/Core/InitializeCore.js');
    if (initCorePath) {
      config.serializer.getModulesRunBeforeMainModule = () => [initCorePath];
    }
  }

  // Asset registry — required for Metro to resolve image assets in RN.
  // Metro defaults to the literal string 'missing-asset-registry-path'.
  config.transformer = config.transformer ?? {};
  if (!config.transformer.assetRegistryPath || config.transformer.assetRegistryPath === 'missing-asset-registry-path') {
    const assetRegistryPath = findInNodeModules(
      projectRoot, 'react-native/Libraries/Image/AssetRegistry.js',
    );
    if (assetRegistryPath) {
      config.transformer.assetRegistryPath = assetRegistryPath;
    }
  }

  // Watch folders — include the output dir so Metro watches our generated files
  config.watchFolders = config.watchFolders ?? [];
  if (!config.watchFolders.includes(options.outputDir)) {
    config.watchFolders.push(options.outputDir);
  }

  return config;
}
