/**
 * Custom Vitest pool worker — bridges to a React Native app over WebSocket.
 *
 * Two modes:
 *   dev  (vitest --watch) — visible emulator, reuse app/Metro, leave running
 *   run  (vitest run)     — headless, clean start, shut down after
 *
 * Metro is started as a child process (npx expo start).
 * Test files are discovered from vitest include patterns and exposed
 * via a virtual test registry module.
 */

import { WebSocketServer, type WebSocket } from 'ws';
import { parse as flatParse, stringify as flatStringify } from 'flatted';
import { spawn, execSync, type ChildProcess } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync, globSync } from 'node:fs';
import { resolve, relative } from 'node:path';
import { checkEnvironment } from './environment';
import { ensureDevice, launchApp, stopApp, shutdownDevice } from './device';

import { log, setVerbose, isVerbose } from './logger';
import { attachCodeFrames, isInternalLog, type BiRpcMessage } from './code-frame';
import type { NativePoolOptions, Platform } from './types';

const DEFAULT_BUNDLE_ID = 'com.vitest.nativetest';

// TypeScript's DOM lib declares setTimeout as returning `number`; Node.js returns
// a Timeout object with .unref(). Cast through unknown to access it safely.
function unrefTimer(t: ReturnType<typeof setTimeout>): void {
  (t as unknown as { unref(): void }).unref();
}

// Module-level singletons — persist across pool worker recreations (watch cycles)
let _wss: WebSocketServer | null = null;
let _connectedSocket: WebSocket | null = null;
let _metroServer: ChildProcess | null = null;
let _currentEmit: ((event: string, data: unknown) => void) | null = null;
let _resolveConnection: (() => void) | null = null;
let _hasCompletedCycle = false;

type EventCallback = (data: unknown) => void;

export function createNativePoolWorker(options: NativePoolOptions) {
  const port = options.port ?? 7878;
  const metroPort = options.metroPort ?? 8081;
  const platform: Platform = options.platform ?? 'android';
  const deviceId = options.deviceId;
  const skipIfUnavailable = options.skipIfUnavailable ?? false;
  const mode = options.mode ?? 'run';
  const headless = options.headless ?? mode === 'run';
  const shouldShutdownEmulator = options.shutdownEmulator ?? mode === 'run';

  const bundleId = options.bundleId ?? DEFAULT_BUNDLE_ID;
  const appDir = options.appDir ?? resolve(process.cwd(), 'app');
  const testInclude = options.testInclude ?? ['modules/**/tests/**/*.test.tsx', 'modules/**/tests/**/*.test.ts'];

  if (options.verbose) setVerbose(true);

  const listeners = new Map<string, Set<EventCallback>>();
  const listenerWrappers = new Map<EventCallback, EventCallback>();

  log.verbose(`Mode: ${mode} | Headless: ${headless} | Platform: ${platform}`);

  function emit(event: string, data: unknown): void {
    const cbs = listeners.get(event);
    if (cbs) cbs.forEach(cb => cb(data));
  }
  _currentEmit = emit;

  // ── Test registry generation ───────────────────────────────────

  function generateTestRegistry(): string {
    const registryDir = resolve(appDir, '.vitest-native');
    mkdirSync(registryDir, { recursive: true });

    const gitignorePath = resolve(registryDir, '.gitignore');
    if (!existsSync(gitignorePath)) {
      writeFileSync(gitignorePath, '*\n');
    }

    const cwd = process.cwd();
    const testFiles: string[] = [];
    for (const pattern of testInclude) {
      try {
        const matches = globSync(pattern, { cwd });
        testFiles.push(...matches);
      } catch {
        /* ignore glob errors */
      }
    }

    const entries = testFiles.map(file => {
      const absPath = resolve(cwd, file);
      const relKey = './' + relative(cwd, absPath);
      return `  ${JSON.stringify(relKey)}: () => require(${JSON.stringify(absPath)})`;
    });

    const registryContent = `// Auto-generated by vitest-react-native-runtime — do not edit
exports.testFiles = {
${entries.join(',\n')}
};
`;

    const registryPath = resolve(registryDir, 'test-registry.js');
    writeFileSync(registryPath, registryContent);
    log.verbose(`Test registry: ${testFiles.length} file(s)`);
    return registryPath;
  }

  // ── Metro (in-process via JS API) ──────────────────────────────

  function startMetro(registryPath: string): Promise<void> {
    return new Promise((resolvePromise, reject) => {
      log.info('Starting Metro...');

      const env: NodeJS.ProcessEnv = {
        ...process.env,
        FORCE_COLOR: '0',
        VITEST_NATIVE_REGISTRY_PATH: registryPath,
      };

      _metroServer = spawn('npx', ['expo', 'start', '--dev-client', '--port', String(metroPort)], {
        cwd: appDir,
        stdio: ['ignore', 'pipe', 'pipe'],
        detached: true,
        env,
      });
      _metroServer.unref();

      let resolved = false;
      const onData = (data: Buffer): void => {
        const text = data.toString();
        text.split('\n').forEach(line => {
          const l = line.trim();
          if (!l) return;

          const hasLog = l.includes('LOG');
          const hasError = l.includes('ERROR');

          if (hasError) {
            console.error(`[metro] ${l}`);
          } else if (hasLog) {
            if (isInternalLog(l)) {
              if (isVerbose()) console.log(`[metro] ${l}`);
            } else {
              console.log(`[metro] ${l}`);
            }
          }
        });
        if (!resolved && (text.includes('Waiting on') || text.includes('Logs for your project'))) {
          resolved = true;
          resolvePromise();
        }
      };

      _metroServer.stdout!.on('data', onData);
      _metroServer.stderr!.on('data', onData);
      _metroServer.on('error', err => {
        if (!resolved) {
          resolved = true;
          reject(err);
        }
      });
      _metroServer.on('exit', code => {
        if (!resolved) {
          resolved = true;
          reject(new Error(`Metro exited with code ${code}`));
        }
      });
      const t = setTimeout(() => {
        if (!resolved) {
          resolved = true;
          reject(new Error('Metro startup timeout (60s)'));
        }
      }, 60000);
      unrefTimer(t);
    });
  }

  async function isMetroRunning(): Promise<boolean> {
    try {
      const res = await fetch(`http://localhost:${metroPort}/status`);
      const text = await res.text();
      return text.includes('packager-status:running');
    } catch {
      return false;
    }
  }

  function killStaleOnPort(targetPort: number): void {
    try {
      const pids = execSync(`lsof -ti:${targetPort}`, { encoding: 'utf8', stdio: 'pipe' }).trim();
      if (!pids) return;
      const myPid = String(process.pid);
      const pidList = pids.split('\n').filter(p => p && p !== myPid);
      for (const pid of pidList) {
        try {
          process.kill(parseInt(pid), 'SIGTERM');
        } catch {
          /* already dead */
        }
      }
      if (pidList.length > 0) {
        log.verbose(`Killed stale process(es) on port ${targetPort}`);
      }
    } catch {
      /* no processes on port */
    }
  }

  function closeMetro(): void {
    if (_metroServer) {
      const mp = _metroServer;
      _metroServer = null;
      try {
        mp.stdout?.destroy();
      } catch {
        /* ignore */
      }
      try {
        mp.stderr?.destroy();
      } catch {
        /* ignore */
      }
      try {
        process.kill(-mp.pid!, 'SIGTERM');
      } catch {
        /* ignore */
      }
      const t = setTimeout(() => {
        try {
          process.kill(-mp.pid!, 'SIGKILL');
        } catch {
          /* ignore */
        }
      }, 2000);
      unrefTimer(t);
      log.verbose('Metro closed');
    }
  }

  // ── WS server ──────────────────────────────────────────────────

  function setupWss(): void {
    if (_wss) return;
    killStaleOnPort(port);
    _wss = new WebSocketServer({ port });
    _wss.on('connection', (socket: WebSocket) => {
      if (_connectedSocket && _connectedSocket !== socket && _connectedSocket.readyState <= 1) {
        socket.close();
        return;
      }
      log.info('App connected');
      _connectedSocket = socket;
      socket.on('message', (data: Buffer) => {
        const raw = data.toString();
        try {
          let msg: BiRpcMessage;
          try {
            msg = flatParse(raw) as BiRpcMessage;
          } catch {
            msg = JSON.parse(raw) as BiRpcMessage;
          }
          attachCodeFrames(msg);
          _currentEmit?.('message', msg);
        } catch (e) {
          log.error('Parse error:', e);
        }
      });
      socket.on('close', () => {
        if (_connectedSocket === socket) _connectedSocket = null;
      });
      _resolveConnection?.();
    });
    _wss.on('error', (err: Error) => log.error('WS error:', err));
  }

  function closeWss(): Promise<void> {
    if (!_wss) return Promise.resolve();
    return new Promise(resolvePromise => {
      for (const client of _wss!.clients) {
        try {
          client.terminate();
        } catch {
          /* ignore */
        }
      }
      _wss!.close(() => {
        _wss = null;
        resolvePromise();
      });
      const t = setTimeout(() => {
        _wss = null;
        resolvePromise();
      }, 1000);
      unrefTimer(t);
    });
  }

  // ── Pool Worker ────────────────────────────────────────────────

  const worker = {
    name: 'native' as const,
    reportMemory: false,

    on(event: string, callback: EventCallback): void {
      const wrappedCb: EventCallback = data => {
        if (event === 'message') {
          const msg = data as BiRpcMessage;
          if (msg?.m === 'onCollected') {
            log.verbose(`onCollected: ${(msg?.a?.[0] as unknown[] | undefined)?.length} file(s)`);
          }
        }
        callback(data);
      };
      listenerWrappers.set(callback, wrappedCb);
      if (!listeners.has(event)) listeners.set(event, new Set());
      listeners.get(event)!.add(wrappedCb);
    },

    off(event: string, callback: EventCallback): void {
      const wrapped = listenerWrappers.get(callback);
      if (wrapped) {
        listeners.get(event)?.delete(wrapped);
        listenerWrappers.delete(callback);
      }
    },

    deserialize(data: unknown): unknown {
      return data;
    },

    async start(): Promise<void> {
      // ── Step 1: Check environment
      const envResult = checkEnvironment(platform);
      if (!envResult.ok) {
        log.error('\nEnvironment check failed:\n');
        for (const issue of envResult.issues) {
          log.error(`  ✗ ${issue.message}`);
          if (issue.fix) log.error(`    Fix: ${issue.fix}\n`);
        }
        if (skipIfUnavailable) {
          log.warn('Skipping native tests (skipIfUnavailable)\n');
          emit('message', { __vitest_worker_response__: true, type: 'started' });
          return;
        }
        throw new Error('Environment not ready. See above for setup instructions.');
      }

      // ── Step 2: Ensure device
      await ensureDevice(platform, { wsPort: port, metroPort, deviceId, headless });

      // ── Step 3: Generate test registry
      const registryPath = generateTestRegistry();

      // ── Step 4: WS server
      if (_connectedSocket) {
        log.verbose('Reusing existing app connection');
      } else {
        setupWss();
      }

      // ── Step 5: Metro
      if (_metroServer) {
        log.verbose('Metro already running, reusing');
      } else {
        const metroAlready = await isMetroRunning();
        if (metroAlready) {
          log.verbose('External Metro already running on port, reusing');
        } else {
          killStaleOnPort(metroPort);
          await startMetro(registryPath);
        }
      }

      // ── Step 6: App
      async function launchWithRetry(): Promise<void> {
        for (let attempt = 0; attempt < 2; attempt++) {
          try {
            launchApp(platform, bundleId, { metroPort, deviceId });
            return;
          } catch (err) {
            if (attempt === 0) {
              log.warn('Launch failed, re-checking device...');
              await ensureDevice(platform, { wsPort: port, metroPort, deviceId, headless });
            } else {
              throw new Error(`Failed to launch app after retry: ${(err as Error).message}`, { cause: err });
            }
          }
        }
      }

      async function waitForApp(): Promise<void> {
        log.info('Waiting for app to connect...');
        return new Promise((resolvePromise, reject) => {
          const original = _resolveConnection;
          _resolveConnection = () => {
            original?.();
            resolvePromise();
          };
          const t = setTimeout(() => {
            if (!_connectedSocket) reject(new Error('App did not connect within 30s'));
          }, 30000);
          unrefTimer(t);
          if (_connectedSocket) {
            clearTimeout(t);
            resolvePromise();
          }
        });
      }

      if (mode === 'dev' && _connectedSocket && _hasCompletedCycle) {
        log.verbose('Reusing app connection');
      } else {
        stopApp(platform, bundleId);
        _connectedSocket = null;
        const delay = new Promise<void>(r => {
          const t = setTimeout(r, 1000);
          unrefTimer(t);
        });
        await delay;
        await launchWithRetry();
        await waitForApp();
      }
    },

    async stop(): Promise<void> {
      if (mode === 'run') {
        closeMetro();
        if (_connectedSocket) {
          try {
            _connectedSocket.terminate();
          } catch {
            /* ignore */
          }
          _connectedSocket = null;
        }
        await closeWss();
        stopApp(platform, bundleId);
        if (shouldShutdownEmulator) {
          shutdownDevice(platform);
        }
        _hasCompletedCycle = false;
      }
      if (mode === 'dev') {
        _hasCompletedCycle = true;
      }

      emit('message', { __vitest_worker_response__: true, type: 'stopped' });
    },

    send(message: BiRpcMessage): void {
      if (message?.__vitest_worker_request__) {
        switch (message.type) {
          case 'start':
            if (_connectedSocket) _connectedSocket.send(flatStringify(message));
            emit('message', { __vitest_worker_response__: true, type: 'started' });
            break;
          case 'run':
          case 'collect':
            if (_connectedSocket) {
              _connectedSocket.send(flatStringify(message));
            } else {
              emit('message', {
                __vitest_worker_response__: true,
                type: 'testfileFinished',
                error: new Error('RN app not connected'),
              });
            }
            break;
          case 'cancel':
            if (_connectedSocket) _connectedSocket.send(flatStringify(message));
            break;
          case 'stop':
            this.stop();
            break;
        }
        return;
      }

      if (_connectedSocket) {
        try {
          _connectedSocket.send(flatStringify(message));
        } catch (e) {
          log.error('Failed to relay birpc:', e);
        }
      }
    },
  };

  return worker;
}
