/**
 * generateTestRegistry — discovers test files via glob and writes a generated
 * JS module that the runtime imports as `vitest-react-native-runtime/test-registry`.
 *
 * The generated module uses dynamic import() for Metro lazy bundling and
 * exports a clean API: testFileKeys, importTestFile, loadAllTestFiles.
 */

import { globSync } from 'glob';
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve, relative, dirname, posix } from 'node:path';

export interface GenerateRegistryOptions {
  /** Absolute path to the app root (where packages/ lives). */
  projectRoot: string;
  /** Glob patterns relative to projectRoot. */
  testPatterns: string[];
  /** Directory to write the generated file into. */
  outputDir: string;
  /** Harness mode to embed ('run' | 'dev'). If set, injected as globalThis.__VITEST_NATIVE_MODE__. */
  mode?: string;
}

export interface GenerateRegistryResult {
  /** Absolute path to the generated file. */
  filePath: string;
  /** Discovered test file paths (relative to projectRoot). */
  testFiles: string[];
}

/**
 * Compute a display key from a test file path.
 * `test-packages/greeting/tests/greeting.test.tsx` → `greeting/greeting.test.tsx`
 * `packages/greeting/tests/greeting.test.tsx` → `greeting/greeting.test.tsx`
 */
function toDisplayKey(filePath: string): string {
  const parts = filePath.split('/');
  // Find the `tests` directory and use the parent as the module name
  const testsIdx = parts.indexOf('tests');
  if (testsIdx >= 1) {
    const pkgName = parts[testsIdx - 1];
    const fileName = parts[parts.length - 1];
    return `${pkgName}/${fileName}`;
  }
  return parts[parts.length - 1];
}

/**
 * Discover test files and write the generated registry module.
 */
export function generateTestRegistry(options: GenerateRegistryOptions): GenerateRegistryResult {
  const { projectRoot, testPatterns, outputDir } = options;

  // Ensure output directory exists
  mkdirSync(outputDir, { recursive: true });
  const gitignorePath = resolve(outputDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, '*\n');
  }

  // Discover test files
  const testFiles: string[] = [];
  for (const pattern of testPatterns) {
    try {
      const matches = globSync(pattern, { cwd: projectRoot });
      testFiles.push(...matches);
    } catch {
      // Ignore glob errors
    }
  }

  // Deduplicate
  const uniqueFiles = [...new Set(testFiles)].sort();

  // Build import entries
  const entries = uniqueFiles.map(file => {
    const displayKey = toDisplayKey(file);
    // Compute relative path from outputDir to the test file (for import())
    const absTestPath = resolve(projectRoot, file);
    let relImport = relative(outputDir, absTestPath);
    // Use posix separators and strip extension for Metro resolution
    relImport = relImport.split('\\').join('/');
    relImport = relImport.replace(/\.(tsx?|jsx?)$/, '');
    if (!relImport.startsWith('.')) {
      relImport = './' + relImport;
    }
    return { displayKey, relImport };
  });

  // Generate the module content
  const importEntries = entries
    .map(e => `  ${JSON.stringify(e.displayKey)}: function() { return import(${JSON.stringify(e.relImport)}); }`)
    .join(',\n');

  // Inject mode if specified (pool sets VITEST_NATIVE_MODE=connected)
  const modeInjection = options.mode
    ? `\nglobalThis.__VITEST_NATIVE_MODE__ = ${JSON.stringify(options.mode)};\n`
    : '';

  const content = `// Auto-generated by vitest-react-native-runtime — do not edit
${modeInjection}var testImports = {
${importEntries}
};

// Sync key list for the explorer UI
exports.testFileKeys = Object.keys(testImports);

// Async thunk — returns fresh module every time (respects HMR)
exports.importTestFile = function(key) {
  var fn = testImports[key];
  if (!fn) throw new Error('[test-registry] Unknown test file: ' + key);
  return fn();
};

// Preload all test bundles (call at startup so modules are cached)
exports.loadAllTestFiles = function() {
  return Promise.allSettled(
    Object.values(testImports).map(function(fn) { return fn(); })
  );
};

if (!globalThis.__TEST_HMR_LISTENERS__) {
  globalThis.__TEST_HMR_LISTENERS__ = new Set();
}

if (module.hot) {
  module.hot.accept();
}
`;

  const filePath = resolve(outputDir, 'test-imports.generated.js');

  // Only write if content changed (avoids unnecessary Metro rebuilds)
  let existing = '';
  try { existing = readFileSync(filePath, 'utf8'); } catch {}
  if (existing !== content) {
    writeFileSync(filePath, content);
  }

  return { filePath, testFiles: uniqueFiles };
}
